//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExTrack.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExTrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hamercurls	13	5	13	5	13	5	13	5	
        ///Hamercurls	13	5	13	5	13	5	13	5	
        ///Hamercurls	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	
        ///Trizeps Curls / Trizepsdrücken	13	5	13	5	13	5	13	5	
        ///Trizeps Curls / Trizepsdrücken	13	5	13	5	13	5	13	5	
        ///Trizeps Curls / Trizepsdrücken	13	5	13	5	13	5	13	5	
        ///Schulterdrücken	15	10	
        ///Schulterdrücken	15	10	
        ///Schulterdrücken	15	10	
        ///
        /// ähnelt.
        /// </summary>
        internal static string ArmeLeicht {
            get {
                return ResourceManager.GetString("ArmeLeicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bizeps Curls	10	10	
        ///Bizeps Curls	10	10	
        ///Bizeps Curls	10	10	
        ///Trizeps Curls / Trizepsdrücken	10	10	
        ///Trizeps Curls / Trizepsdrücken	10	10	
        ///Trizeps Curls / Trizepsdrücken	10	10	
        ///Hamercurls	10	15	
        ///Hamercurls	10	15	
        ///Hamercurls	10	15	
        ///Schulterdrücken	10	15	
        ///Schulterdrücken	10	15	
        ///Schulterdrücken	10	15	
        ///
        /// ähnelt.
        /// </summary>
        internal static string ArmeMedium {
            get {
                return ResourceManager.GetString("ArmeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hamercurls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Hamercurls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Hamercurls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Bizeps Curls	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Trizeps Curls / Trizepsdrücken	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	13	5	
        ///Trizeps Curls / Trizepsdrücken	13	5	13	5	13	5 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ArmeSchwer {
            get {
                return ResourceManager.GetString("ArmeSchwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BatmanAudio {
            get {
                return ResourceManager.GetStream("BatmanAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BatmanPicture {
            get {
                object obj = ResourceManager.GetObject("BatmanPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Situps	10	
        ///Situps	10	
        ///Situps	10	
        ///Situps	20	
        ///Beinheben	15	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BauchLeicht {
            get {
                return ResourceManager.GetString("BauchLeicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Situps	20	
        ///Situps	20	
        ///Situps	20	
        ///Situps	20	
        ///Beinheben	20	
        ///Beinheben	20	
        ///Beinheben	20	
        ///Beinheben	20	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BauchMittel {
            get {
                return ResourceManager.GetString("BauchMittel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Situps	30	
        ///Situps	30	
        ///Situps	30	
        ///Situps (Negativ)	15	
        ///Situps (Negativ)	15	
        ///Situps (Negativ)	15	
        ///Beinheben	25	
        ///Beinheben	25	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BauchSchwer {
            get {
                return ResourceManager.GetString("BauchSchwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankdrücken (Kurzhantel)	10	10	
        ///Bankdrücken (Kurzhantel)	10	10	
        ///Bankdrücken (Kurzhantel)	10	10	
        ///Butterflies	10	10	
        ///Butterflies	10	10	
        ///Butterflies	10	10	
        ///Liegestüze	13	
        ///Liegestüze	13	
        ///Liegestüze	13	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BrustLeicht {
            get {
                return ResourceManager.GetString("BrustLeicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankdrücken (Kurzhantel)	10	15	
        ///Bankdrücken (Kurzhantel)	10	15	
        ///Bankdrücken (Kurzhantel)	10	15	
        ///Butterflies	10	15	
        ///Butterflies	10	15	
        ///Butterflies	10	15	
        ///Liegestüze	18	
        ///Liegestüze	18	
        ///Liegestüze	18	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BrustMittel {
            get {
                return ResourceManager.GetString("BrustMittel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bankdrücken (Kurzhantel)	13	17.5	
        ///Bankdrücken (Kurzhantel)	13	17.5	
        ///Bankdrücken (Kurzhantel)	13	17.5	
        ///Butterflies	15	15	
        ///Butterflies	15	15	
        ///Butterflies	15	15	
        ///Liegestüze	25	
        ///Liegestüze	25	
        ///Liegestüze	25	
        ///
        /// ähnelt.
        /// </summary>
        internal static string BrustSchwer {
            get {
                return ResourceManager.GetString("BrustSchwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnDonate {
            get {
                object obj = ResourceManager.GetObject("btnDonate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream JohnCenaAudio {
            get {
                return ResourceManager.GetStream("JohnCenaAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JohnCenaPicture {
            get {
                object obj = ResourceManager.GetObject("JohnCenaPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TripleHAudio {
            get {
                return ResourceManager.GetStream("TripleHAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TripleHPicture {
            get {
                object obj = ResourceManager.GetObject("TripleHPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
